### ISSUE TITLE
Testing: HT 

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/libreset#101]
Implement Hashtable testing

Should be done _before_ the actual hashtable implementation, and should be merged onto an extra branch for the hashtable implementation, so we can slowly move to a n-branch-workflow.

**Comment by matthiasbeyer** [comment]
We should/could do a test-driven approach here: One who implements a functionality can first write the test and then implement the functionality required to pass the test.

Relates #102 , #62 , #63

**Comment by neithernut** [comment]
May now be closed.
