### ISSUE TITLE
Testing: Set

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/libreset#102]
Implement set testing.

Should be done on a seperate branch for the set implementation, so we are slowly moving towards a n-branch-workflow here, too.

**Comment by TheNeikos** [comment]
What do you mean a separate branch for the set implementation? (Since this is the testing issue)

**Comment by matthiasbeyer** [comment]
I would like to add the hashtable implementation (#101) and the set implementation on own branches, which will receive the PRs from the contributors. That's all. You don't have to do much, besides submitting your PRs onto the appropriate branch.

But I would suggest if you want to start contributing, you should start with the HT, not with the Set, as this is one level above the HT and the interface of this may change during your contribution! :-)

**Comment by matthiasbeyer** [comment]
Further explanation on WF:

Our current WF is like so:

``` plain
o ---- o ----- o (master)
\-o-o-/ \-o-o-/  (feature branches)
```

I would like to change this for a WF like so:

``` plain
o --------------- o (master)
|               /
 \-o-------o---o  (feature)
  |    \   |   |
  \-o-+-o-/    | (feature_functionality_a)
         \-o-o-/  (feature_functionality_b)
```

**Comment by TheNeikos** [comment]
Alright!

**Comment by neithernut** [comment]
I think this can be closed now.

**Comment by TheNeikos** [comment]
No it can't. Tests are not yet fully implemented.

**Comment by TheNeikos** [comment]
This can now be closed as all set functions should only be merged with adequate testing.
