### ISSUE TITLE
Adapt to Layer model

### ISSUE THREAD

**Issue by neithernut** [waysome/libreset#103]
The library is divided into a few layers implicitly.
The AVL uses the linked-list, the hashtable uses the AVL.
I'd like to change a few things to do the same in code. E.g. the hashtable should not fiddle with the linked list. When inserting an element, the hashtable should insert the element into the AVL, which in turn will possibly add new nodes on it's own. The AVL will then add the element to the linked list, which should check for duplicates by iterating and applying the cmp-function provided by the user.
Requires: type information provided by the user being passed down the layers.

**Comment by matthiasbeyer** [comment]
That's already the case, isn't it?

When I do a `avl_add()` if finds the appropriate node (or creates one) and adds the element to the linkedlist inside it.

**Comment by neithernut** [comment]
It doesn't check whether the element exists in the linked list, which should be done in the linked list. To do this, the type information has to be passed.
`avl_del` should be able to destroy elements using the user provided type information, too.

**Comment by neithernut** [comment]
Also, `avl_find` returns a node, which requires the ht to fiddle around with the linked list.

**Comment by matthiasbeyer** [comment]
On the first point: That's a simple ptr-compare, you don't need type information for this! And yes, this should be done by the linked list, this is indeed a thing which _could_ be improved.

The implementation for `avl_find()` should change, that's true! Are you willing to do this?

**Comment by neithernut** [comment]
The pointer being identical is _not_ the only way, two elements might be identical. E.g. consider `strcmp()`.
a PR will be submitted probably this afternoon/evening.

**Comment by matthiasbeyer** [comment]
You think people will do things like this:

```
int a = 4;
rs_insert(set, (char*)&a);
rs_insert(set, ((char*)&a)+1);
```

or what? Because this is the only thing I can imagine one could insert an "object" twice without the same ptr.

Storing the type information (assuming you mean size here) too, would prevent us from cases like this with little overhead. But it would also cause changes, _and I think we're running out of time for library_.

**Comment by neithernut** [comment]
This is neccessary for the library to function correctly. This is how a set works.

**Comment by neithernut** [comment]
It actually shouldn't be hard, since `r_set_cfg` already exists.

**Comment by matthiasbeyer** [comment]
indeed. Awaiting PR on this.

**Comment by neithernut** [comment]
Servicing info: I'm working on adaption of the AVL interface, so you guys can adapt the ht stuff.

**Comment by matthiasbeyer** [comment]
Lol. 5 merged PRs. closing this one now.
