### ISSUE TITLE
Functions for deleting non-hash-equivalent elements

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/libreset#108]
As suggested by @neithernut  in #107 , we maybe should have functions for deleting elements with non-equivalent hashes as well.

I'd like to suggest:
- Keep the current functions, `_del`, let them remove (multiple) elements with the same hash only
- Add functions `_ndel` for deleting multiple elements which may not have the same hash

**Comment by neithernut** [comment]
Agreed.

**Comment by matthiasbeyer** [comment]
Relevant issues:

#144 , #134 , #136

**Comment by neithernut** [comment]
May now be closed.
