### ISSUE TITLE
Fix avl_del

### ISSUE THREAD

**Issue by neithernut** [waysome/libreset#109]
Adapt `avl_del` to comply with PR #108.

**Comment by matthiasbeyer** [comment]
are you doing this right now?

**Comment by neithernut** [comment]
Nope, feel free to start a PR.

**Comment by neithernut** [comment]
Just modify the interface, I'll take care of the internals as soon as I finished the LL interface.

**Comment by matthiasbeyer** [comment]
I'll do this now.

**Comment by matthiasbeyer** [comment]
@neithernut is this issue only for the interface, which gets solved by #111 ? Or is it also meant for the implementation and should be kept open after #111 is merged?

**Comment by neithernut** [comment]
The implementation is covered by #63, so this issue may now be closed.
