### ISSUE TITLE
Go through the interfaces which are stable atm and add __attributes__

### ISSUE THREAD

**Issue by neithernut** [waysome/libreset#114]
E.g. all the functions containing warnings about NULL pointers resulting in crashes may be attributed with `nonnull`.
The resulting compiler errors should also be fixed.
This will save us a lot of pain.

**Comment by neithernut** [comment]
Note: for doing this looking at the source code of the signle functions should be enough.
Also: this will probably solve the issue surfacing in PR #99 as well.

**Comment by matthiasbeyer** [comment]
We should probably do this in pair-programming!

**Comment by neithernut** [comment]
Probably a good idea.

**Comment by matthiasbeyer** [comment]
Do you think we can already start this? We could meet up today and do this, but if there are interface changes left to do, we should wait until they are done!

**Comment by neithernut** [comment]
We can do it for the linked list and the AVL. Those interfaces should be stable by now. Which means: additions as soon as we introduce the fancier features, but no changes to existing function declarations.

**Comment by matthiasbeyer** [comment]
Okay, meet me at our IRC for planning when to meet!

**Comment by neithernut** [comment]
Mh... `avl_ndel()` is messed up, will fix. After that, the interface _really_ is stable.

**Comment by neithernut** [comment]
This issue was split up into #138 and #139.
