### ISSUE TITLE
Should we use UseLaTeX for builds of the paper/documentation?

### ISSUE THREAD

**Issue by neithernut** [waysome/libreset#116]
https://github.com/kmorel/UseLATEX is a CMake module which aims to build LaTeX in CMake based build setups. It would add a dependency, albeit for the documentation only. As for now, the package is not (yet?) included in the CMake package.
Including this in a Travis CI setup should be no problem. However, we _may_ have users, which will, too, need to have this dependency installed.
Subrepos are _not_ an option.

**Comment by matthiasbeyer** [comment]
I like the idea. How much overhead is this?

Are there packages for all major distributions for UseLatex?

**Comment by neithernut** [comment]
I don't think so.
Stuff like this is _can_ be included in the `cmake` directory, which is usually done for dependencies which do not ship files for cmake themselfes (so you can easily do a `find_package` on it).
This _may_ be one solution temporary solution.
The wiki explicitly states that the package _might_ go into CMake itself if you keep bothering the dev. We might just do so and, one happy day, to a version bump on CMake and throw out our copy of UseLaTeX.

**Comment by neithernut** [comment]
Info: it's just one file: `UseLaTeX.cmake`

**Comment by matthiasbeyer** [comment]
The problem I see is, that you still need `pdflatex` to actually build the paper, don't you? So it would be unnecessary overhead...

**Comment by neithernut** [comment]
UseLaTeX is a CMake Module, which wraps all the LaTeX stuff nicely. Have a look at the documentation:
- it run's LaTeX multiple times
- It finds pdflatex itself, which is currently done manually

It's a _little bit_ of overhead, but in this case, you _want_ the little overhead to keep things clean.

**Comment by matthiasbeyer** [comment]
Ok, I'd like to see a PR on this, BUT I think it is secondary. There is more stuff to do.

This issue will be re-opened later when this stuff becomes more relevant. Lets focus on the important things now!
