### ISSUE TITLE
Segfault in regen_metadata()

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/libreset#118]
This is the issue which targets the bug mentioned in #99 .

---

For the lazy:

I experience a SEGFAULT here because of an unchecked ptr accessing in regen_metadata() called from insert_element_into_tree() in avl_add():

```
#0  regen_metadata (node=0x604ad0) at /home/m/dev/c/libreset/src/libreset/avl.c:402
#1  0x00007ffff79cfdd7 in insert_element_into_tree (el=0x604890, root=0x604870) at /home/m/dev/c/libreset/src/libreset/avl.c:233
#2  0x00007ffff79cfcce in avl_add (avl=0x604870, d=0x7fffffffe1d4, hash=1) at /home/m/dev/c/libreset/src/libreset/avl.c:185
#3  0x0000000000401c78 in test_avl_add_multiple (_i=0) at /home/m/dev/c/libreset/tests/avl/avl_tests.c:74
#4  0x00007ffff7bd66ab in ?? () from /usr/lib/libcheck.so.0
#5  0x00007ffff7bd69f7 in srunner_run () from /usr/lib/libcheck.so.0
#6  0x000000000040284e in main () at /home/m/dev/c/libreset/tests/tests.c:33
```

---

More information on how to reproduce/debug:

Run the checks manually with CK_FORK="no" <debugger of choice> tests/check_tests and set breakpoints at the test after breaking there, set a breakpoint in insert_element_into_tree and go on from there.

@neithernut It's your code, you are familiar with it, will you target this?

**Comment by neithernut** [comment]
Yep, I'll have a look at it.

**Comment by neithernut** [comment]
Turned out to be a very, very, very stupid mistake. Fix is on the way.

**Comment by neithernut** [comment]
May now be closed.
