### ISSUE TITLE
errno.h for error values

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/libreset#128]
Use errno.h header constants for error return values.

**Comment by neithernut** [comment]
Can this be closed?

**Comment by matthiasbeyer** [comment]
I think so.

Please check the public interface whether there are errno returns missing.

**Comment by matthiasbeyer** [comment]
@neithernut , @TheNeikos Is this done? Can you check the code for missing errno returns? (I'll do as well, of course)

**Comment by matthiasbeyer** [comment]
I think this can be closed now.
