### ISSUE TITLE
Rework alloc and destroy functions

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/libreset#142]
Rework alloc and destroy functions:
- We don't need `_alloc()` functions for data structures which get embedded into other data structures
- We don't need `_destroy()` functions (if they free the data structure) for embedded data structures

@TheNeikos wanna do this?

**Comment by neithernut** [comment]
Rephrasing: `_destroy()` functions _must not_ free the data structure. If they are empty, they may be removed.

**Comment by matthiasbeyer** [comment]
> If they are empty, they may be removed.

You mean the functions with this, right?

**Comment by neithernut** [comment]
Yep.

**Comment by neithernut** [comment]
May now be closed.
