### ISSUE TITLE
Where is the ll_is_empty() function?

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/libreset#143]
Where is the ll_is_empty() function?

Just wondered where it went, because I need it for the implementation of `avl_ndel()`.

**Comment by neithernut** [comment]
Seems it doesn't exist. I'll implement it and submit a PR right away.

**Comment by matthiasbeyer** [comment]
:+1: 

Seems it was removed by someone. Hm, strange!

**Comment by neithernut** [comment]
I'm away in about 30min. If you merge PR #141, I can rebase and resolve merge conflicts before being afk.
