### ISSUE TITLE
Implement ll_ndel()

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/libreset#144]
Implement ll_ndel()

**Comment by neithernut** [comment]
I'll take this one. But I'll perform the changes sometime tonight/tomorrow.

**Comment by matthiasbeyer** [comment]
Ok. I need this for `avl_ndel` which is required for `ht_ndel`. So this blocks a lot of things.

**Comment by matthiasbeyer** [comment]
@neithernut Sorry, could not wait.

**Comment by neithernut** [comment]
May now be closed.
