### ISSUE TITLE
`avl_add` seems to be broken

### ISSUE THREAD

**Issue by TheNeikos** [waysome/libreset#157]
[This Line](https://github.com/TheNeikos/libreset/blob/e5f1451612b9efb8813e9a3dfb948fdaf4b9003f/tests/avl/avl_tests.c#L72) should not make the test fail.

Upon further inspection with gdb it seems that avl_add does correctly add elements, but it does not correctly move the tree around.

**Comment by neithernut** [comment]
Mh... so the error is somewhere on my part. So it's my job to fix it.

**Comment by matthiasbeyer** [comment]
@neithernut Correct. :-P

**Comment by neithernut** [comment]
This issue may now be closed (as the failing code turned out not to be on my part in this case)

**Comment by TheNeikos** [comment]
That is correct!
