### ISSUE TITLE
Naming of insert functions not consistent.

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/libreset#159]
We have:
- `ht_insert()`
- `avl_add()`
- `ll_insert()`

We should be consistent here.

**Comment by TheNeikos** [comment]
Yes, because you insert into a list, but you don't insert into an AVL tree as you don't really know where it will end up. But I guess renaming it shouldn't be a problem.

**Comment by neithernut** [comment]
We,, we changed the semantics a little a few days ago.
Before, it was _adding_ a node.
Now it's _inserting_ an element.
(the AVL and the linked list are, in a way, each a set implementation of their own)

**Comment by neithernut** [comment]
This may now be closed.
