### ISSUE TITLE
Implement: r_set_new()

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/libreset#164]

**Comment by matthiasbeyer** [comment]
@neithernut How many hashtable buckets should be allocated by default? Or should we pass a parameter to `r_set_new()` for this?

**Comment by neithernut** [comment]
Nope, I see no problem in dictating the default here.
The optimal number of elements in an AVL is about 15 for 64-bit machines. A minimum number of buckets of 4 (or 8) would mean potentially more than 50 (or 100) elements before the first resize. This seems like a sane value to me.

**Comment by matthiasbeyer** [comment]
The point is, that this may be not a sane value for other people. Running this library for a program which gets executed on a 512-MB-RAM-Raspberry Pi might need another init value here as running this on a 16TiB RAM HPC Cluster.

You get the point? I would like to make this configureable via a compiletime constant, at least.

**Comment by neithernut** [comment]
`8*sizeof(struct bucket) = 8*8bytes = 64 bytes` ...

**Comment by matthiasbeyer** [comment]
But you still have only 8 Buckets. If you want to have 10k buckets, you're stuck and the HT has to resize several times... which takes time.

**Comment by neithernut** [comment]
In this case, the insertion of ~100k objects will take more time than the resizing...

**Comment by matthiasbeyer** [comment]
Good point. I guess we could also add such an possibility (for defining init size) later on, if there is need.

So I should use an init size of `4` for 32-bit architectures and `8` for 64 bit?

**Comment by neithernut** [comment]
Just use `8`.
