### ISSUE TITLE
Why does the github indicator say there is C++ source in the repository?

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/libreset#17]
Why does the github indicator say there is C++ source in the repository?

Maybe this thing is just buggy, as we do not have C++ code in this repository, but maybe something looks really C++ish?

**Comment by TheNeikos** [comment]
`.h` files are flagged as C++

**Comment by matthiasbeyer** [comment]
Why? I thought `.hpp` is the extension for C++-Header files?

**Comment by neithernut** [comment]
Yep, but some people use .h

**Comment by matthiasbeyer** [comment]
I guess this all will be solved after adding the actual implementation. I will close this now.

**Comment by matthiasbeyer** [comment]
For documentation: Today, the switch was made. The indicator now lists the repository as C code. Victory!
