### ISSUE TITLE
Paper: Choice of parameters chapter missing

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/libreset#179]
The chapter "choice of parameters" is still missing in the paper.

**Comment by neithernut** [comment]
I'm working on it. And if people stop bugging me for stuff, I _may_ even get stuff done.

**Comment by matthiasbeyer** [comment]
Sorry, don't wanted to piss you off!

**Comment by matthiasbeyer** [comment]
I assume this can be closed?

**Comment by neithernut** [comment]
Yep.
