### ISSUE TITLE
Finish paper

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/libreset#180]
Actually, we do not have an "urgent" tag, but the milestone is already past due 7 days.

Manually assigned now: @neithernut . :-) How much has to be done, you propably know best! Please add the appropriate issues _or_, if it is not _that_ much to do, submit the appropriate PRs.

**Comment by neithernut** [comment]
I'm working on it.
Btw: the phrasing of the milestone is utter bullshit. The paper will in no way be polished and neither is it neccessary that the paper is polished at this stage.

**Comment by matthiasbeyer** [comment]
I assume this can be closed?

**Comment by neithernut** [comment]
Yep.
