### ISSUE TITLE
How should the set operations be implemeneted on the lower levels?

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/libreset#197]
How should the architecture look like for the lower parts of the library, namingly the hashtable, avl and linked list implementation?

For example, if you do an union between two sets, does the set code handle all this, or are there sub-problems which can be solved on the level of the hash table or avl?

---

Also, but not that important: We _could_ split up the code for the set function implementations in own files under `src/libreset/operations/*.c` to keep things less complex. I assume there will be a lot of code for these functions, so it would be nice to have them split up.

For common code parts, we could create a `src/libreset/operations/common.{c,h}`, where common code snippets would resist then.

What do you think?

**Comment by neithernut** [comment]
Most operations will be implemented on all levels. I suggest picking an operation and then implement it for the ll, the AVL and the ht in that order.

---

With the AVL, we could keep putting all the functions into `avl.h`, but make the `struct avl_el` a forward declaration. We could then put that struct into a new internal header `avl_el.h`. All the algorithms dealing with the nodes directly would then go into the `avl_el.c` or a set of source files (`avl_el_base.c`, `avl_el_common.c`, ...). The implementation of the interface itself are mostly functions of only a few lines, so it should not hurt to put all of them into `avl.c`.

We could do the same for the linked list.

The algorithms are quite simple for the hashtable, so it's feasible to have only one source file here.

**Comment by matthiasbeyer** [comment]
Your suggestion would split up the individual files for the datatypes, if I understand this right?

Two ideas, I guess we should vote:

1) Put all code for a datatype (set, hashtable, avl, linked list) into _one_ file.
2) Put code for a datatype into the `src/libreset/<datatype>/<datatype>.c` and algorithms which have to do with set operations on the type into `src/libreset/<datatype>/<operation>. {c,h}`

The latter would cause the file tree look like this:

``` plain
src/libreset/

src/libreset/ht/ht.h
src/libreset/ht/ht.c
src/libreset/ht/union.h
src/libreset/ht/union.c
src/libreset/ht/...

src/libreset/avl/avl.h
src/libreset/avl/avl.c
src/libreset/avl/union.h
src/libreset/avl/union.c
src/libreset/avl/...

src/libreset/ll/ll.h
src/libreset/ll/ll.c
src/libreset/ll/union.h
src/libreset/ll/union.c
src/libreset/ll/...

src/libreset/...
```

We would also add datatype-specific subfolders, for example: `src/libreset/avl/el/el.{c,h}`.

Which would be cleaner in some ways, as there is less code in more files but you
always know _where_ the code for an algorithm is.

I would prefer the latter, so **VOTE: 2**.
I would also implement this then (moving files around).

**Comment by TheNeikos** [comment]
That seems to make sense to me.

**Comment by neithernut** [comment]
My suggestion would indeed split up the files for individual datatypes. It would also clean up the interface and enable people to find code more quickly (direct interface implementation is always in `<datatype>.c`, internal stuff may be found in another file)

Also, the codebase for the HT is quite small, splitting things up here doesn't make much sense.

My suggestion would result in a setup like:

```
src/libreset/ht.h
src/libreset/ht.c

src/libreset/avl.h
src/libreset/avl.c
src/libreset/avl_el.h
src/libreset/avl_el/base.c
src/libreset/avl_el/common.c
src/libreset/avl_el/union.c
src/libreset/avl_el/intersection.c
...

src/libreset/ll.h
src/libreset/ll.c
src/libreset/ll_element.h
src/libreset/ll_element/base.c
src/libreset/ll_element/common.c
src/libreset/ll_element/union.c
src/libreset/ll_element/intersection.c
...

```

**Comment by neithernut** [comment]
With my suggestion, the internal functions may also be divided into "base"-, "common"- and other sections.

**Comment by matthiasbeyer** [comment]
Do we actually have set operations for _elements_ (talking about the `ll_element` type here). I don't think so.

I consider my approach as more clean, as there would be _one_ directory for all hashtable stuff, _one_ directory for all avl stuff, etc. Which would result in less files under `src/libreset/`. 

---

When talking about "common" functions, we talk about "insert", "delete", "find" and this stuff, along with "init" and "destroy", are we?

---

Also, I don't see value in splitting stuff up into "base" and "common" - these two are literally the same for me.

**Comment by neithernut** [comment]
Obviously we need functionality to determine the intersection and union of two linked lists!

---

Yep, while e.g. rotations and rebalancing would to into "base".

**Comment by matthiasbeyer** [comment]
Of course we need this, but this has nothing to do with the element types, just the linkedlist type itself. You cannot build the intersection of two linkedlist-elements but of two linked lists.

**Comment by neithernut** [comment]
Ah, now I get what you're talking about.
The intersection and union doesn not neccessarily have to happen on a node level. In contrary to the AVL, you also do not need recursion, since the data structure is linear. However, you probably will end up with a few utiliy functions, so having at least `base.c` for the linked list is probably a good idea.

**Comment by matthiasbeyer** [comment]
@TheNeikos , @manuelmessner which approach do you guys find more clean?

**Comment by TheNeikos** [comment]
We have reached a conclusion to do it this way:

``` plain
src/libreset
   -> <type>/
           -> <type>.h
           -> common.h
           -> common.c // Implementations of functions used in the implementation for the <type>
           -> base.c   // Implementation of the basic interface of functions from <type>.h
           -> union.c
           -> intersection.c
           -> ....  
```

This issue can then be closed.

**Comment by manuelmessner** [comment]
ACK

**Comment by neithernut** [comment]
ACK.

**Comment by matthiasbeyer** [comment]
I will target this now.
