### ISSUE TITLE
Speed up travis.

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/libreset#199]
Travis gets painful slow. We should look into the speedup options.

**Comment by neithernut** [comment]
Travis CI docs on caching: http://docs.travis-ci.com/user/caching/
It sais: "only available for private repositories on travis-ci.com"

**Comment by matthiasbeyer** [comment]
Damn.

**Comment by matthiasbeyer** [comment]
Maybe this can help: http://docs.travis-ci.com/user/speeding-up-the-build/

---

The actual problem is not the build (well, the latex stuff takes some time...) but the installing of the dependencies. I guess we have no luck here.

**Comment by TheNeikos** [comment]
Running our own solution?

**Comment by TheNeikos** [comment]
In the end all you need is a hook that sends a ping to a server and which then git clones and runs a shell script and sends back the return value of the script.

**Comment by neithernut** [comment]
Indeed.

**Comment by neithernut** [comment]
May now be closed due to #204.

**Comment by matthiasbeyer** [comment]
More likely due to #200 , as we are still on travis. But yes.
