### ISSUE TITLE
Add drone.io support

### ISSUE THREAD

**Issue by TheNeikos** [waysome/libreset#204]
Drone.io is faster and seems to be more reliable than travis.

It doesn't include pull request build feedback, but with some bash scripting this can be easily integrated.

To get it to work you have to do these steps:
- drone.io account and set it up for the repository
- create a personal [access token](https://github.com/settings/applications) you will need at least `public_repo, repo:status` auth
- Write it into the ENV Variables box on drone.io as `OAUTH_TOKEN=<token>`
- Add the script below

``` bash
postStatus() {
  curl -so /dev/null -X POST -H "Authorization: token $OAUTH_TOKEN" -d "{\"state\": \"$1\", \"target_url\": \"$DRONE_BUILD_URL\", \"description\": \"Built and tested on drone.io\", \"context\": \"Built and tested on drone.io\"}" https://api.github.com/repos/TheNeikos/libreset/statuses/$DRONE_COMMIT;
}

fail() {
   postStatus failure
   exit 1
}

postStatus pending

sudo apt-get install -y check
echo 2 | sudo update-alternatives --config gcc
cmake -DHARD_MODE=ON . || fail
make || fail
ctest -VV . || fail
postStatus success

```

This will allow you to use drone.io.

**Comment by neithernut** [comment]
GJ.

**Comment by matthiasbeyer** [comment]
I'd like to try this next week soonest. I appreciate your work very much and I would love to drop travis as it is a real pain in the ass from my point of view.

A self-hosted solution would have even more benefits, but I guess we have to stick to drone.io for the first few months until we can afford it.

**Comment by TheNeikos** [comment]
Okay, so I had an idea. And it turns out, this idea worked.
I managed to get the custom ci server to work. It uses the self hosted drone package and does _not_ need a bash hack to report the status! (Win-Win!)

To get it to work you will need a `.drone.yml` file with this content:

``` yaml
image: neikos/libreset
script:
    - cmake -DHARD_MODE=ON .
    - make
    - ctest -VV .
```

then you go to http://ci.neikos.me and register/login and add a repository.

You are then all set!!!

**Comment by neithernut** [comment]
YaY!

**Comment by matthiasbeyer** [comment]
AWESOME!

@TheNeikos and I will switch on monday morning, will we?

I would _love_ several build machines for several distros! What do you think about the following list:
- Debian
- Arch
- Fedora

? (Not too much as I think we shouldn't kill @TheNeikos server, but hey...) And not Ubuntu, as we stated some time ago that we won't support Ubuntu!

**Comment by matthiasbeyer** [comment]
@TheNeikos stated that drone does not support matrix builds by now. I would stick to fedora for the first step then.

**Comment by matthiasbeyer** [comment]
Before I close this: drone is so god damn awesome!

**Comment by TheNeikos** [comment]
Glad you like it :smile:
