### ISSUE TITLE
Remove forking mode from check

### ISSUE THREAD

**Issue by TheNeikos** [waysome/libreset#213]
The reasoning behind this is that it really does not make it slower, but a lot harder to debug once it does happen. As you have to add the line manually and stash it again later.

I would open a pull request for this.

**Comment by matthiasbeyer** [comment]
What is your problem. I don't understand the statement above.

**Comment by TheNeikos** [comment]
basically to let check run in no fork modus by default.

On my fish setting env variables is a bit tricky (you can't set them per line).

**Comment by matthiasbeyer** [comment]
And you would add this to the travis build env or what? I'm highly against this, as this would cause check to fail at the first error, but with the current setup we get _all_ the errors, which is much better when developing source.

**Comment by TheNeikos** [comment]
To debug you would have to stop at the first error as well as the program is terminated anyway afterwards. (A failed assert does not terminate afaik.)

**Comment by matthiasbeyer** [comment]
I'd like to hear opinions from @neithernut and @manuelmessner on this.

**Comment by neithernut** [comment]
A failing test does not yield quite useful debugging output by default. Check would have to be run in `gdb`, which would mean that either `ctest` would have to run `gdb` for us or we would call `check_tests` manually from the testing script.
Given that `gdb` can be a bit bitchy when it comes to being operated non-interactively, both of the options are not advisable imho.

---

Debugging locally does make more sense imho.
Also: the "new" git pre-commit hook runs ctest and doesn't let you commit if it fails (locally).

**Comment by matthiasbeyer** [comment]
(We should probably update our pre-commit hook installations!

**Comment by manuelmessner** [comment]
@neithernut +1

**Comment by matthiasbeyer** [comment]
I'm heavily against running check in non-fork mode on the CI. There are just disadvantages doing this, and as our new CI is not slow as hell anymore, we shouldn't care about this.

For local runs, I can understand that non-fork mode would be an advantage in some manner. At least for the pre-commit hook, of course.

**Comment by TheNeikos** [comment]
Consensus seems to be to keep it! Closing.
