### ISSUE TITLE
Fix __attribute__ header

### ISSUE THREAD

**Issue by neithernut** [waysome/libreset#224]
The attribute header currently breaks a lot of stuff because some standart headers seem to use conflicting macros.
I was already working on a fix, but it did not get all the attention due to higher priorities.
I will continue working on this.

**Comment by neithernut** [comment]
Glibc has a few lines like

``` C
#define __param__ param
```

Which breaks things for us.
Someone should modify the attribute macros, e.g. from `__foo__` to `__r_foo__`

**Comment by matthiasbeyer** [comment]
:+1: for `__r_` as prefix. @manuelmessner you wanna do this?

**Comment by neithernut** [comment]
Blocks #114.

**Comment by neithernut** [comment]
Solved.
