### ISSUE TITLE
Milestones: v0.0.0-paper, v0.0.0-doc

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/libreset#237]
Lets talk about milestones:

---
## v0.0.0-doc

There are no issues left for this one and I consider the sources as really good
documented. If someone has a code-coverage tool which checks how many functions
are undocumented (in percent), please run it. I would bet we have documented
more than 90 percent of the code.

So my question is: shall I close this milestone?

---
## v0.0.0-paper

This milestone is due 12 days ago at the moment, but is also marked as 100 %
ready. Do you guys consider this milestone as reached, or are there things left
we should add / do for the paper?

---

Please discuss here.

**Comment by neithernut** [comment]
The only thing which is still missing in the paper are the actual thresholds for resizing. However, the data structure doesn't require resizes as much as regular hash-tables, so this can wait.
We should close the paper-milestone.

**Comment by matthiasbeyer** [comment]
@TheNeikos , @manuelmessner

**Comment by TheNeikos** [comment]
Can't say anything about the paper. But I believe the documentation is alright.

**Comment by matthiasbeyer** [comment]
So I'll close the paper and the doc milestone now.
