### ISSUE TITLE
Attributes for public interface?

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/libreset#253]
I don't know if this was asked before.

Should we add attribute labels to our public interface function definitions? This would cause our `__r_` attribute macros to be publicly visible. This shouldn't be an issue, as they are prefixed, but could be considered as dirty.

@TheNeikos, @neithernut  what do you think?

**Comment by neithernut** [comment]
From a user's point of view, it makes sense to have the attributes (e.g. for warnings when passing `NULL` where you shouldn't)

**Comment by matthiasbeyer** [comment]
Covered in #254 .

**Comment by matthiasbeyer** [comment]
can be closed, right?

**Comment by neithernut** [comment]
Yep.
