### ISSUE TITLE
License ok?

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/libreset#43]
Is the license (BSD) ok? I added the license at the very beginning of the project without asking you guys if it is ok to use BSD, we could change it, if you guys want.

I suggest `LGPLv2` as license. At the moment, only me, @neithernut  and @manuelmessner must acknowledge a new License, if we want another one. Doing this now is much easier than doing this after a number of people has contributed!

**Comment by neithernut** [comment]
I'm fine with a BSD license, but LGPLv2 might be better.
E.g. I'm not quite sure whether GPL licenced programs may link to BSD licenced libraries.

**Comment by matthiasbeyer** [comment]
I don't think so, but other way round.

**Comment by matthiasbeyer** [comment]
References:

[gnu.org on modified-bsd](http://www.gnu.org/licenses/license-list.html#ModifiedBSD)

[gnu.org on clear-bsd](http://www.gnu.org/licenses/license-list.html#clearbsd)

[gnu.org compatibility matrix (only GPLish)](http://www.gnu.org/licenses/gpl-faq.html#AllCompatibility)

[wikipedia on BSD](http://en.wikipedia.org/wiki/BSD_licenses)

**Comment by matthiasbeyer** [comment]
I would like a switch to `LGPLv2` because of the copyleft. BSD has no copyleft, as far as I know.

**Comment by neithernut** [comment]
I'll give a "go" for a switch to LGPLv2.

**Comment by matthiasbeyer** [comment]
@manuelmessner what about you? I will add an appropriate PR, where you guys have to ACK again, for documentation.

**Comment by matthiasbeyer** [comment]
For Documentation: #45 Changes the license from BSD to LGPLv2.1.
