### ISSUE TITLE
Implement: AVL rotations

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/libreset#67]
Implement the AVL rotations:
- single rotation with left
- single rotation with right
- double rotation with left
- double rotation with right

**Comment by matthiasbeyer** [comment]
Required for #55 ( #66) and #56

**Comment by matthiasbeyer** [comment]
@neithernut do you want to implement these?

**Comment by neithernut** [comment]
Yep, but I _may_ do it on my way back to germany. It this case, the stuff will be pushed on friday.

**Comment by matthiasbeyer** [comment]
Check the milestones if this is possible without delaying them. If not... I'll try to implement it.

**Comment by matthiasbeyer** [comment]
The milestone for this is due to 23.09.14, so I'll be fine to see this on friday from you, @neithernut !
