### ISSUE TITLE
How to retreive an element from the set?

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/libreset#86]
By now, a hash can identify several elements. But that's somehow not intuitive. The user wants _one_ hash for _one_ element to identify.

So what happens if the user puts in _one_ hash and expects _one_ element to come out, but there are actually two elements:

``` C
void* my_element = rs_get(set, my_element_hash);
```

?

This does not work, obviously. And we cannot just return the first one, we must return all elements. How is this issue solved? Should we make the linkedlist interface public and return a linkedlist instead of the actual `void*` ?

**Comment by neithernut** [comment]
A user will provide an element which may be compared to other elements using a comparision function (which, in turn, is part of the setup/type info provided through a struct).
The find/get function will then return the element found in the set or NULL.
Another function should be added which, instead of returning NULL, inserts the element provided and returns _that_ element, if no element was found.

**Comment by matthiasbeyer** [comment]
So a user will have to provide the data itself to find it inside the set? Isn't then the whole set irrelevant, because you already have the data (besides the set-operations)? So you don't need to store anything, because when you need to access it, you must know it beforehand...

**Comment by neithernut** [comment]
Nope, you have to provide an element which _compares_ to the one you want, not hte element itself.

Consider packages which hold products. If you want a product, you may take an _empty_ package (or a photo), go tto the next salesman, show the package to him and say: "I want such a thing"

**Comment by matthiasbeyer** [comment]
Lol. I trust you on this point, although I do not understand how this should work.

**Comment by neithernut** [comment]
When I'm back at FuWa, I'll explain it to you in more detail.

**Comment by matthiasbeyer** [comment]
Thanks. I'll close this now.
