### ISSUE TITLE
make clean check_tests fails

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/libreset#94]
For me,

```
make clean check_tests
```

fails:

```
Scanning dependencies of target check_tests
[100%] Building C object tests/CMakeFiles/check_tests.dir/tests.c.o
make[3]: *** No rule to make target 'src/libreset.so', needed by 'tests/check_tests'.  Schluss.
CMakeFiles/Makefile2:264: recipe for target 'tests/CMakeFiles/check_tests.dir/all' failed
make[2]: *** [tests/CMakeFiles/check_tests.dir/all] Error 2
CMakeFiles/Makefile2:272: recipe for target 'tests/CMakeFiles/check_tests.dir/rule' failed
make[1]: *** [tests/CMakeFiles/check_tests.dir/rule] Error 2
Makefile:172: recipe for target 'check_tests' failed
make: *** [check_tests] Error 2
```

@neithernut ?

Edit: On latest master, of course.

**Comment by neithernut** [comment]
check_tests links against libreset.so, which CMake can build. However, CMake only knows about "libreset.so", not about "src/libreset.so".
In other words: libreset has to be build before the tests are run.

**Comment by neithernut** [comment]
I will push a prelimary fix.

**Comment by neithernut** [comment]
This will get extra ugly, since CTest is designed to be run after `make`. It is _not_ designed to be run on an incomplete build or after `make clean`.
I would like to ignore this issue but add documentation.

**Comment by neithernut** [comment]
Turns out this works better than expected.
Await a PR.

**Comment by neithernut** [comment]
May now be closed.
